version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: legal-rag-postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: legal-rag-opensearch
    restart: always
    environment:
      discovery.type: single-node
      plugins.security.disabled: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"

volumes:
  postgres_data:
